[CmdletBinding()]
param([int]$PullRequest=0,[switch]$DryRun,[switch]$Once)
$ErrorActionPreference='Stop';$Root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$cp=Join-Path $PSScriptRoot 'config.json';if(Test-Path $cp){$c=Get-Content $cp -Raw|ConvertFrom-Json}else{$c=Get-Content (Join-Path $PSScriptRoot 'config.example.json') -Raw|ConvertFrom-Json};$Repo=$c.repo
$sd=Join-Path $Root $c.state_dir;$ld=Join-Path $Root $c.log_dir;$sf=Join-Path $sd 'state.json';$lock=Join-Path $sd 'run.lock';$log=Join-Path $ld 'auto-fix.jsonl';New-Item -Force -ItemType Directory $sd,$ld|Out-Null
function L($e,$d=@{}){([ordered]@{ts=(Get-Date).ToUniversalTime().ToString('o');event=$e;data=$d}|ConvertTo-Json -Compress)|Tee-Object $log -Append|Write-Host}
function G([string[]]$a){$o=& gh @a 2>&1;if($LASTEXITCODE){throw ($o-join "`n")};$o-join "`n"}
function Label($n,$x){if(-not ((G @('pr','view',"$n",'--repo',$Repo,'--json','labels','--jq','.labels[].name'))-split "`n" -contains $x)){if(-not $DryRun){G @('pr','edit',"$n",'--repo',$Repo,'--add-label',$x)|Out-Null}}}
if(Test-Path $lock){throw 'another poller is already running'};if(-not $DryRun){New-Item $lock -ItemType File|Out-Null}
try{if(-not(Get-Command gh -EA SilentlyContinue)){throw 'gh CLI not found'};if(-not $DryRun -and -not(Get-Command claude -EA SilentlyContinue)){throw 'claude CLI not found'}
 $s=if(Test-Path $sf){Get-Content $sf -Raw|ConvertFrom-Json}else{[pscustomobject]@{prs=@{}}};$ids=if($PullRequest){@($PullRequest)}else{@((G @('pr','list','--repo',$Repo,'--state','open','--json','number','--jq','.[].number'))-split "`n"|?{$_})}
 foreach($pr in $ids){try{$m=G @('pr','view',"$pr",'--repo',$Repo,'--json','state,headRefName,headRefOid,headRepositoryOwner')|ConvertFrom-Json;if($m.state-ne'OPEN'-or$m.headRepositoryOwner.login-ne$c.owner){continue};if($c.allowed_prs.Count-and$c.allowed_prs-notcontains[int]$pr){continue};if(-not$s.prs.$pr){$s.prs|Add-Member NoteProperty "$pr" ([pscustomobject]@{rounds=@{};processed=@{};fails=0})};$p=$s.prs.$pr;$sha=$m.headRefOid;$r=[int]$p.rounds.$sha;if($r-ge$c.max_rounds){Label $pr 'human-review';continue}
  $rv=G @('api',"repos/$Repo/pulls/$pr/reviews")|ConvertFrom-Json|?{$_.user.login-eq$c.codex_login-and$_.state-eq'COMMENTED'-and$_.commit_id-eq$sha-and-not$p.processed.([string]$_.id)}|sort submitted_at|select -Last 1;if(-not$rv){continue};$co=G @('api',"repos/$Repo/pulls/$pr/reviews/$($rv.id)/comments")|ConvertFrom-Json;$body=($co|%{"$($_.path): $($_.body)"})-join "`n";if($body-match'(?i)P0|critical|permission|secret|production|architecture|ruleset|merge|security'){Label $pr 'needs-human-review';continue};if($p.fails-ge2){Label $pr 'human-review';continue};if($DryRun){L 'dry_run' @{pr=$pr;sha=$sha;action='claude-test-commit-push'};continue}
  if(git status --porcelain){throw 'worktree is not clean'};git switch --force-create $m.headRefName $sha|Out-Null;$prompt="Fix only this Codex review. Do not merge, change CI/rulesets, access production, commit, or push.`n$body";$prompt|& claude -p --dangerously-skip-permissions --max-turns 15 --output-format text;if($LASTEXITCODE){throw 'claude failed'};if((git branch --show-current)-ne$m.headRefName){throw 'branch changed'};if(-not(git status --porcelain)){throw 'no changes'};foreach($t in $c.test_commands){& powershell -NoProfile -Command $t;if($LASTEXITCODE){throw 'tests failed'}};git add -A;git commit -m "fix: Codex review PR #$pr"|Out-Null;git push origin "HEAD:$($m.headRefName)"|Out-Null;$p.rounds.$sha=$r+1;$p.processed|Add-Member NoteProperty ([string]$rv.id) $true;$s|ConvertTo-Json -Depth 10|Set-Content $sf;L 'pushed' @{pr=$pr;sha=$sha;round=$r+1}}catch{$p=$s.prs.$pr;if($p){$p.fails++};$s|ConvertTo-Json -Depth 10|Set-Content $sf;L 'error' @{pr=$pr;message=$_.Exception.Message}}}}finally{if(-not$DryRun){Remove-Item $lock -Force -EA SilentlyContinue}}
